# Generated by Django 4.2.7 on 2024-03-19 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_response',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
