# Generated by Django 4.2.7 on 2024-03-29 05:06

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_admin_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[project.utils.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
