# Generated by Django 4.2.7 on 2023-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('summary', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полное описание')),
                ('summary_image', models.ImageField(upload_to='content/', verbose_name='Изображение на главную страницу')),
                ('content_image', models.ImageField(upload_to='content/', verbose_name='Изображение для наши услуги')),
            ],
            options={
                'verbose_name': 'Наша услуга',
                'verbose_name_plural': 'Наши услуги',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['pk'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
