# Generated by Django 4.2.7 on 2024-03-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_aboutcompany_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/', verbose_name='Изображение компании'),
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='company_files/', verbose_name='Файл')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.aboutcompany', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Файл компании',
                'verbose_name_plural': 'Файлы компании',
            },
        ),
    ]
