# Generated by Django 4.2.7 on 2024-03-29 04:50

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_vacancy_options_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, validators=[project.utils.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
